language: java

jdk:
  - oraclejdk8

cache:
  directories:
  - '$HOME/.m2/repository'

#before_install:
# - chmod +x gradlew

script:
  - mvn clean package -laolaocha=true

after_success:
  - git init
  - git config user.name "ankoyun"
  - git config user.email "1467962577@qq.com"
  - git add spring-boot-jsp.war
  - git commit -m "version 1"
  - git push --force --quiet "https://${GITHUB_TOKEN}@${GH_REF}" master:master
env:
  global:
  - GH_REF=github.com/zheng-zy/test-travis-ci-maven.git